version: "3"
services:
  mycent:
    container_name: mycent-container
    image: mycent-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10022:22
    volumes:
      - type: volume
        source: mycent-vol
        target: /data
        volume:
          nocopy: true
    tty: true

    #networks:
    #command:

  volumes:
    mycent-vol:
      name: mycent-volume

  networks:
    frontend:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.10.0/24

    backend:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.20.0/24